# Tempo - Dev overrides
# Dev: shorter retention, smaller storage

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/dev-eks-tempo

tempo:
  retention: 72h

persistence:
  size: 10Gi
