# Grafana Alloy - Staging overrides

alloy:
  extraEnv:
    - name: AMP_REMOTE_WRITE_URL
      valueFrom:
        secretKeyRef:
          name: managed-monitoring-endpoints
          key: AMP_REMOTE_WRITE_URL
    - name: AWS_REGION
      value: "us-west-2"
    - name: CLUSTER_NAME
      value: "staging-eks"
