# Grafana Agent - Staging overrides

extraEnv:
  - name: AMP_REMOTE_WRITE_URL
    value: "https://aps-workspaces.us-west-2.amazonaws.com/workspaces/ws-PLACEHOLDER/api/v1/remote_write"
  - name: AWS_REGION
    value: "us-west-2"
  - name: CLUSTER_NAME
    value: "staging-eks"
