# Velero - Dev overrides
# Dev: backups disabled, no node agent, no backup locations

serviceAccount:
  server:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::000000000000:role/dev-eks-velero

configuration:
  backupStorageLocation: []
  volumeSnapshotLocation: []

deployNodeAgent: false

schedules:
  daily:
    disabled: true
  weekly:
    disabled: true
