apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aws-neuron

resources:
  - namespace.yaml
  - daemonset.yaml
  - rbac.yaml

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/managed-by: eks-agent-platform
      app.kubernetes.io/part-of: eks-agent-platform
